name: goreleaser

on:
  push:
    tags:
      - "v*" # Triggers on pushes to tags starting with v

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate changelog generation

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod # Automatically detects the Go version from go.mod
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # You can use 'release' or 'snapshot' arguments
          args: release --clean
        env:
          # GITHUB_TOKEN is required to publish the release and assets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          